### 게시글 ID, 댓글 ID
@postId = 1
@commentId = 1

### 댓글 등록
POST http://localhost:8080/posts/{{postId}}/comments
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}
Content-Type: application/json

{
  "description": "test description"
}

### 댓글 목록 조회
GET http://localhost:8080/posts/{{postId}}/comments

### 댓글 수정
PUT http://localhost:8080/posts/{{postId}}/comments/{{commentId}}
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}
Content-Type: application/json

{
  "description": "update description"
}

### 댓글 삭제
DELETE http://localhost:8080/posts/{{postId}}/comments/{{commentId}}
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}