
### 좋아요 등록(뉴스피드)
POST http://localhost:8080/likes
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}
Content-Type: application/json

{
  "contentId" : 1,
  "contentType":"NEWSFEED"
}

### 좋아요 등록(댓글)
POST http://localhost:8080/likes
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}
Content-Type: application/json

{
  "contentId" : 1,
  "contentType":"COMMENT"
}


### 좋아요 삭제
DELETE http://localhost:8080/likes/4
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}
Content-Type: application/json


### 좋아요 조회
GET http://localhost:8080/likes/1/COMMENT
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}
Content-Type: application/json






















// 회원 여러명을 위해..
### 회원가입2
POST http://localhost:8080/users
Content-Type: application/json

{
  "accountId": "user222222",
  "password": "1q2w3e4r!@#$",
  "name": "user2",
  "email": "user2@email.com"
}

### 회원가입3
POST http://localhost:8080/users
Content-Type: application/json

{
  "accountId": "user333333",
  "password": "1q2w3e4r!@#$",
  "name": "user3",
  "email": "user3@email.com"
}

### 로그인2
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "accountId": "user222222",
  "password": "1q2w3e4r!@#$"
}

> {%
    client.log(response.headers.valueOf("accessToken"));
    client.log(response.headers.valueOf("refreshToken"));
    client.global.set("accessToken", response.headers.valueOf("accessToken"));
    client.global.set("refreshToken", response.headers.valueOf("refreshToken"));
%}

### 로그인3
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "accountId": "user333333",
  "password": "1q2w3e4r!@#$"
}

> {%
    client.log(response.headers.valueOf("accessToken"));
    client.log(response.headers.valueOf("refreshToken"));
    client.global.set("accessToken", response.headers.valueOf("accessToken"));
    client.global.set("refreshToken", response.headers.valueOf("refreshToken"));
%}