### 게시글 생성
POST http://localhost:8080/posts
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}
Content-Type: application/json

{
  "title": "testTitle",
  "description": "testDescription"
}

### 게시글 목록 조회
GET http://localhost:8080/posts

### /posts/{id} <- path
@id = 1

### 게시글 수정
PUT http://localhost:8080/posts/{{id}}
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}
Content-Type: application/json

{
  "title": "updateTitle",
  "description": "updateDescription"
}

### 게시글 삭제
DELETE http://localhost:8080/posts/{{id}}
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}
